module NativeBindings.Keys

// Taken from https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
let convertStringKeyToCode (keyString: string) =
    match keyString with
    | "VK_LBUTTON" -> Some 0x01
    | "VK_RBUTTON" -> Some 0x02
    | "VK_CANCEL" -> Some 0x03
    | "VK_MBUTTON" -> Some 0x04
    | "VK_XBUTTON1" -> Some 0x05
    | "VK_XBUTTON2" -> Some 0x06
    | "VK_BACK" -> Some 0x08
    | "VK_TAB" -> Some 0x09
    | "VK_CLEAR" -> Some 0x0C
    | "VK_RETURN" -> Some 0x0D
    | "VK_SHIFT" -> Some 0x10
    | "VK_CONTROL" -> Some 0x11
    | "VK_MENU" -> Some 0x12
    | "VK_PAUSE" -> Some 0x13
    | "VK_CAPITAL" -> Some 0x14
    | "VK_KANA" -> Some 0x15
    | "VK_HANGUEL" -> Some 0x15
    | "VK_HANGUL" -> Some 0x15
    | "VK_JUNJA" -> Some 0x17
    | "VK_FINAL" -> Some 0x18
    | "VK_HANJA" -> Some 0x19
    | "VK_KANJI" -> Some 0x19
    | "VK_ESCAPE" -> Some 0x1B
    | "VK_CONVERT" -> Some 0x1C
    | "VK_NONCONVERT" -> Some 0x1D
    | "VK_ACCEPT" -> Some 0x1E
    | "VK_MODECHANGE" -> Some 0x1F
    | "VK_SPACE" -> Some 0x20
    | "VK_PRIOR" -> Some 0x21
    | "VK_NEXT" -> Some 0x22
    | "VK_END" -> Some 0x23
    | "VK_HOME" -> Some 0x24
    | "VK_LEFT" -> Some 0x25
    | "VK_UP" -> Some 0x26
    | "VK_RIGHT" -> Some 0x27
    | "VK_DOWN" -> Some 0x28
    | "VK_SELECT" -> Some 0x29
    | "VK_PRINT" -> Some 0x2A
    | "VK_EXECUTE" -> Some 0x2B
    | "VK_SNAPSHOT" -> Some 0x2C
    | "VK_INSERT" -> Some 0x2D
    | "VK_DELETE" -> Some 0x2E
    | "VK_HELP" -> Some 0x2F
    | "0" -> Some 0x30
    | "1" -> Some 0x31
    | "2" -> Some 0x32
    | "3" -> Some 0x33
    | "4" -> Some 0x34
    | "5" -> Some 0x35
    | "6" -> Some 0x36
    | "7" -> Some 0x37
    | "8" -> Some 0x38
    | "9" -> Some 0x39
    | "a" -> Some 0x41
    | "b" -> Some 0x42
    | "c" -> Some 0x43
    | "d" -> Some 0x44
    | "e" -> Some 0x45
    | "f" -> Some 0x46
    | "g" -> Some 0x47
    | "h" -> Some 0x48
    | "i" -> Some 0x49
    | "j" -> Some 0x4A
    | "k" -> Some 0x4B
    | "l" -> Some 0x4C
    | "m" -> Some 0x4D
    | "n" -> Some 0x4E
    | "o" -> Some 0x4F
    | "p" -> Some 0x50
    | "q" -> Some 0x51
    | "r" -> Some 0x52
    | "s" -> Some 0x53
    | "t" -> Some 0x54
    | "u" -> Some 0x55
    | "v" -> Some 0x56
    | "w" -> Some 0x57
    | "x" -> Some 0x58
    | "y" -> Some 0x59
    | "z" -> Some 0x5A
    | "VK_LWIN" -> Some 0x5B
    | "VK_RWIN" -> Some 0x5C
    | "VK_APPS" -> Some 0x5D
    | "VK_SLEEP" -> Some 0x5F
    | "VK_NUMPAD0" -> Some 0x60
    | "VK_NUMPAD1" -> Some 0x61
    | "VK_NUMPAD2" -> Some 0x62
    | "VK_NUMPAD3" -> Some 0x63
    | "VK_NUMPAD4" -> Some 0x64
    | "VK_NUMPAD5" -> Some 0x65
    | "VK_NUMPAD6" -> Some 0x66
    | "VK_NUMPAD7" -> Some 0x67
    | "VK_NUMPAD8" -> Some 0x68
    | "VK_NUMPAD9" -> Some 0x69
    | "VK_MULTIPLY" -> Some 0x6A
    | "VK_ADD" -> Some 0x6B
    | "VK_SEPARATOR" -> Some 0x6C
    | "VK_SUBTRACT" -> Some 0x6D
    | "VK_DECIMAL" -> Some 0x6E
    | "VK_DIVIDE" -> Some 0x6F
    | "VK_F1" -> Some 0x70
    | "VK_F2" -> Some 0x71
    | "VK_F3" -> Some 0x72
    | "VK_F4" -> Some 0x73
    | "VK_F5" -> Some 0x74
    | "VK_F6" -> Some 0x75
    | "VK_F7" -> Some 0x76
    | "VK_F8" -> Some 0x77
    | "VK_F9" -> Some 0x78
    | "VK_F10" -> Some 0x79
    | "VK_F11" -> Some 0x7A
    | "VK_F12" -> Some 0x7B
    | "VK_F13" -> Some 0x7C
    | "VK_F14" -> Some 0x7D
    | "VK_F15" -> Some 0x7E
    | "VK_F16" -> Some 0x7F
    | "VK_F17" -> Some 0x80
    | "VK_F18" -> Some 0x81
    | "VK_F19" -> Some 0x82
    | "VK_F20" -> Some 0x83
    | "VK_F21" -> Some 0x84
    | "VK_F22" -> Some 0x85
    | "VK_F23" -> Some 0x86
    | "VK_F24" -> Some 0x87
    | "VK_NUMLOCK" -> Some 0x90
    | "VK_SCROLL" -> Some 0x91
    | "VK_LSHIFT" -> Some 0xA0
    | "VK_RSHIFT" -> Some 0xA1
    | "VK_LCONTROL" -> Some 0xA2
    | "VK_RCONTROL" -> Some 0xA3
    | "VK_LMENU" -> Some 0xA4
    | "VK_RMENU" -> Some 0xA5
    | "VK_LALT" -> Some 0xA4 // LALT/RALT are actually LMENU/RMENU, but those are silly names
    | "VK_RALT" -> Some 0xA5
    | "VK_BROWSER_BACK" -> Some 0xA6
    | "VK_BROWSER_FORWARD" -> Some 0xA7
    | "VK_BROWSER_REFRESH" -> Some 0xA8
    | "VK_BROWSER_STOP" -> Some 0xA9
    | "VK_BROWSER_SEARCH" -> Some 0xAA
    | "VK_BROWSER_FAVORITES" -> Some 0xAB
    | "VK_BROWSER_HOME" -> Some 0xAC
    | "VK_VOLUME_MUTE" -> Some 0xAD
    | "VK_VOLUME_DOWN" -> Some 0xAE
    | "VK_VOLUME_UP" -> Some 0xAF
    | "VK_MEDIA_NEXT_TRACK" -> Some 0xB0
    | "VK_MEDIA_PREV_TRACK" -> Some 0xB1
    | "VK_MEDIA_STOP" -> Some 0xB2
    | "VK_MEDIA_PLAY_PAUSE" -> Some 0xB3
    | "VK_LAUNCH_MAIL" -> Some 0xB4
    | "VK_LAUNCH_MEDIA_SELECT" -> Some 0xB5
    | "VK_LAUNCH_APP1" -> Some 0xB6
    | "VK_LAUNCH_APP2" -> Some 0xB7
    | "VK_OEM_1" -> Some 0xBA
    | "VK_OEM_PLUS" -> Some 0xBB
    | "VK_OEM_COMMA" -> Some 0xBC
    | "VK_OEM_MINUS" -> Some 0xBD
    | "VK_OEM_PERIOD" -> Some 0xBE
    | "VK_OEM_2" -> Some 0xBF
    | "VK_OEM_3" -> Some 0xC0
    | "VK_OEM_4" -> Some 0xDB
    | "VK_OEM_5" -> Some 0xDC
    | "VK_OEM_6" -> Some 0xDD
    | "VK_OEM_7" -> Some 0xDE
    | "VK_OEM_8" -> Some 0xDF
    | "VK_OEM_102" -> Some 0xE2
    | "VK_PROCESSKEY" -> Some 0xE5
    | "VK_PACKET" -> Some 0xE7
    | "VK_ATTN" -> Some 0xF6
    | "VK_CRSEL" -> Some 0xF7
    | "VK_EXSEL" -> Some 0xF8
    | "VK_EREOF" -> Some 0xF9
    | "VK_PLAY" -> Some 0xFA
    | "VK_ZOOM" -> Some 0xFB
    | "VK_NONAME" -> Some 0xFC
    | "VK_PA1" -> Some 0xFD
    | "VK_OEM_CLEAR" -> Some 0xFE
    | _ -> None


